services:
    darkdiesel.pagescroller.listener:
        class: darkdiesel\pagescroller\event\main_listener
        arguments:
            - @config
            - @ext.manager
            - @template
            - %core.root_path%
        tags:
            - { name: event.listener }

